### ISSUE TITLE
Error .... ENOENT

### ISSUE THREAD

**Issue by kevinsullivan** [Microsoft/dafny#175]
A student had a working installation of Dafny VS Code and the Dafny compiler as installed by the plug-in. Without warning, he reported, his compiler stopped working. He showed me the error he was getting when he tried to compile a known-good simple file. The error report is below. Deleting and having VS Code reinstall ~/.dafny cleared the problem. It's unclear to me how the use of the plug-in leads to state changes in that compiler/server directory, what state change caused the problem, or how reinstalling the software cleared the bad state.

============

verify all1

all verifyfile:///c%3A/CS2102/quiz1.dfy

Local: 1.9.16

Remote:v1.9.16

c:\Users\sonny\.dafny\dafny/Dafny.exe /compile:1,/nologo,c:\CS2102\cs-dm-read-only\dafny\specification\functional.dfy

events.js:163

throw er; // Unhandled 'error' event

^

Error: spawn c:\Users\sonny\.dafny\dafny/Dafny.exe ENOENT

at exports._errnoException (util.js:1050:11)

at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)

at onErrorNT (internal/child_process.js:367:16)

at _combinedTickCallback (internal/process/next_tick.js:80:11)

at process._tickCallback (internal/process/next_tick.js:104:9)

[Info - 3:59:31 PM] Connection to server got
 closed. Server will restart.

verify all2

all verifyfile:///c%3A/CS2102/quiz1.dfy

all verifyfile:///c%3A/CS2102/cs-dm-read-only/dafny/specification/functional.dfy

events.js:163

throw er; // Unhandled 'error' event

^

Error: write EPIPE

at exports._errnoException (util.js:1050:11)

at Socket._writeGeneric (net.js:724:26)

at Socket._write (net.js:743:8)

at doWrite (_stream_writable.js:329:12)

at writeOrBuffer (_stream_writable.js:315:5)

at Socket.Writable.write (_stream_writable.js:241:11)

at Socket.write (net.js:670:40)

at ProcessWrapper.writeRequestToServer (C:\Users\sonny\.vscode\extensions\FunctionalCorrectness.dafny-vscode-0.10.10\server\process\process.js:50:42)

at ProcessWrapper.sendRequestToDafnyServer (C:\Users\sonny\.vscode\extensions\FunctionalCorrectness.dafny-vscode-0.10.10\server\process\process.js:33:14)

at DafnyServer.sendVerificationRequest (C:\Users\sonny\.vscode\extensions\FunctionalCorrectness.dafny-vscode-0.10.10\server\backend\dafnyServer.js:178:29)

[Info - 3:59:33 PM] Connection to server got
 closed. Server will restart.

verify all2

all verifyfile:///c%3A/CS2102/quiz1.dfy

all verifyfile:///c%3A/CS2102/cs-dm-read-only/dafny/specification/functional.dfy

events.js:163

throw er; // Unhandled 'error' event

^

Error: write EPIPE

at exports._errnoException (util.js:1050:11)

at Socket._writeGeneric (net.js:724:26)

at Socket._write (net.js:743:8)

at doWrite (_stream_writable.js:329:12)

at writeOrBuffer (_stream_writable.js:315:5)

at Socket.Writable.write (_stream_writable.js:241:11)

at Socket.write (net.js:670:40)

at ProcessWrapper.writeRequestToServer (C:\Users\sonny\.vscode\extensions\FunctionalCorrectness.dafny-vscode-0.10.10\server\process\process.js:50:42)

at ProcessWrapper.sendRequestToDafnyServer (C:\Users\sonny\.vscode\extensions\FunctionalCorrectness.dafny-vscode-0.10.10\server\process\process.js:33:14)

at DafnyServer.sendVerificationRequest (C:\Users\sonny\.vscode\extensions\FunctionalCorrectness.dafny-vscode-0.10.10\server\backend\dafnyServer.js:178:29)

[Info - 3:59:34 PM] Connection to server got
 closed. Server will restart.

**Comment by kevinsullivan** [comment]
This is a VS Code issue. Closing @ Dafny repo.
