### ISSUE TITLE
/compile:3 C# compiler doesn't find library DLL and crashes

### ISSUE THREAD

**Issue by mschlaipfer** [microsoft/dafny#266]
A call like the following, referencing a C# library DLL

`Dafny.exe TestHKDF.dfy HKDF-extern.cs BouncyCastle.Crypto.dll /compile:3`

results in the output:

```
Dafny 2.3.0.10506

Dafny program verifier finished with 2 verified, 0 errors
Compiled program written to TestHKDF.cs
Running...

Error: Execution resulted in exception: Exception has been thrown by the target of an invocation.
System.IO.FileNotFoundException: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.5.0, Culture=neutral, PublicKeyToken=0e99375e54769942' or one of its dependencies. The system cannot find the file specified.
File name: 'BouncyCastle.Crypto, Version=1.8.5.0, Culture=neutral, PublicKeyToken=0e99375e54769942'
   at BouncyCastleCryptoMac.HMac..ctor(HMAC_ALGORITHM algorithm)
   at _17_HmacSha256Kdf_Compile.__default.hkdf(HMAC_ALGORITHM which__sha, Byte[] salt, Byte[] ikm, Byte[] info, BigInteger L, Byte[]& okm) in c:\Users\schlaipf\dev\workspace\aws-encryption-sdk-dafny\src\hkdf\test\TestHKDF.cs:line 2186
   at _20_TestHKDF_Compile.__default.test0() in c:\Users\schlaipf\dev\workspace\aws-encryption-sdk-dafny\src\hkdf\test\TestHKDF.cs:line 2285
   at _20_TestHKDF_Compile.__default.Main() in c:\Users\schlaipf\dev\workspace\aws-encryption-sdk-dafny\src\hkdf\test\TestHKDF.cs:line 2296

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by mschlaipfer** [comment]
This issue might be due to me assuming that DLLs are statically linked into the EXE. But leaving this open for now.

**Comment by robin-aws** [comment]
Might be expected behavior but labeling as `bug` until proven otherwise.
